<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_613777c5cde53',
        'title' => 'Gardp settings',
        'fields' => array(
            array(
                'key' => 'field_6137783663038',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6137781063034',
                'label' => 'General',
                'name' => 'general',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_61e14f304c848',
                        'label' => 'Gardp global urls',
                        'name' => 'gardp_global_urls',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_repeater_stylised_button' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_61498d191b129',
                                'label' => 'Gardp global url',
                                'name' => 'gardp_global_url',
                                'type' => 'text',
                                'instructions' => 'If your web link is https://www.gardp.org/ just paste "gardp.org" WITHOUT quotation marks.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_61433f8b1feae',
                        'label' => 'Facet IDs',
                        'name' => 'facet_ids',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_61433f981feaf',
                                'label' => 'Load more facet ID',
                                'name' => 'load_more_facet_id',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_61433fa71feb0',
                                'label' => 'Category filter ID',
                                'name' => 'category_filter_id',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_61b0abfe00ced',
                        'label' => 'Animations',
                        'name' => 'animations',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_61b0b0df412e7',
                                'label' => 'Desktop',
                                'name' => 'desktop',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'acfe_seamless_style' => 0,
                                'acfe_group_modal' => 0,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_61b0b0df412e8',
                                        'label' => 'Unified bacteria size',
                                        'name' => 'unified_bacteria_size',
                                        'type' => 'range',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => 150,
                                        'min' => 10,
                                        'max' => 500,
                                        'step' => 10,
                                        'prepend' => '',
                                        'append' => 'px',
                                    ),
                                    array(
                                        'key' => 'field_61b355193105f',
                                        'label' => 'Opacity',
                                        'name' => 'opacity',
                                        'type' => 'range',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'min' => '0.1',
                                        'max' => 1,
                                        'step' => '0.1',
                                        'prepend' => '',
                                        'append' => '',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_61b0b0a9412e5',
                                'label' => 'Mobile',
                                'name' => 'mobile',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'acfe_seamless_style' => 0,
                                'acfe_group_modal' => 0,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_61b0ac0500cee',
                                        'label' => 'Unified bacteria size',
                                        'name' => 'unified_bacteria_size',
                                        'type' => 'range',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '35',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => 150,
                                        'min' => 10,
                                        'max' => 500,
                                        'step' => 10,
                                        'prepend' => '',
                                        'append' => 'px',
                                    ),
                                    array(
                                        'key' => 'field_61b0b0bb412e6',
                                        'label' => 'Overflow?',
                                        'name' => 'overflow',
                                        'type' => 'range',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '35',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'min' => 0,
                                        'max' => 25,
                                        'step' => '',
                                        'prepend' => '',
                                        'append' => '%',
                                    ),
                                    array(
                                        'key' => 'field_61b3553831060',
                                        'label' => 'Opacity',
                                        'name' => 'opacity',
                                        'type' => 'range',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '30',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'min' => '0.1',
                                        'max' => 1,
                                        'step' => '0.1',
                                        'prepend' => '',
                                        'append' => '',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_61e527ef8b47e',
                'label' => 'Global colors',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61e6d5106b500',
                'label' => 'Colors',
                'name' => 'colors',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_61e6d5746b508',
                        'label' => 'White',
                        'name' => 'white',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#ffffff',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61e6d62956d2e',
                        'label' => 'Black',
                        'name' => 'black',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#000000',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61e6d63856d2f',
                        'label' => 'Dark',
                        'name' => 'dark',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#061B2E',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61e6d64456d30',
                        'label' => 'Gray',
                        'name' => 'gray',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#F7F8FB',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61e6d940d07b7',
                        'label' => 'Dark Blue',
                        'name' => 'color_a',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#A3A4D2',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61e6d97ba04f8',
                        'label' => 'Medium Blue',
                        'name' => 'color_b',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#99D98C',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61e6d9e3d8a81',
                        'label' => 'Light Blue',
                        'name' => 'color_c',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#22BECA',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61e6d9f6d8a82',
                        'label' => 'Pale Blue',
                        'name' => 'color_d',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#6EC3B4',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_61ea79f904673',
                        'label' => 'Highlight animation track color',
                        'name' => 'highlight_animation_track_color',
                        'type' => 'select',
                        'instructions' => 'This is the global color for all \'highlight animation track\' that is seen at hero for example.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'white' => 'White',
                            'dark' => 'Dark',
                            'black' => 'Black',
                            'gray' => 'Gray',
                            'color-a' => 'Dark Blue',
                            'color-b' => 'Medium Blue',
                            'color-c' => 'Light Blue',
                            'color-d' => 'Pale Blue',
                            'color-e' => 'Accent',
                        ),
                        'default_value' => 'color-e',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'array',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_62038758a991c',
                        'label' => 'Accent',
                        'name' => 'color_e',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#ffd43a',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                ),
            ),
            array(
                'key' => 'field_6137781863035',
                'label' => 'Header',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_613777da6302e',
                'label' => 'Header',
                'name' => 'header',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_613777e06302f',
                        'label' => 'Logo',
                        'name' => 'logo',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'uploader' => '',
                        'acfe_thumbnail' => 0,
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_61e94f118a68e',
                        'label' => 'Color',
                        'name' => 'color',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_61e94f1a8a68f',
                                'label' => 'Navbar background',
                                'name' => 'navbar_background',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'white' => 'White',
                                    'dark' => 'Dark',
                                    'black' => 'Black',
                                    'gray' => 'Gray',
                                    'color-a' => 'Dark Blue',
                                    'color-b' => 'Medium Blue',
                                    'color-c' => 'Light Blue',
                                    'color-d' => 'Pale Blue',
                                    'color-e' => 'Accent',
                                ),
                                'default_value' => 'white',
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'array',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_61e94f5f8a690',
                                'label' => 'Labels',
                                'name' => 'labels',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'white' => 'White',
                                    'dark' => 'Dark',
                                    'black' => 'Black',
                                    'gray' => 'Gray',
                                    'color-a' => 'Dark Blue',
                                    'color-b' => 'Medium Blue',
                                    'color-c' => 'Light Blue',
                                    'color-d' => 'Pale Blue',
                                    'color-e' => 'Accent',
                                ),
                                'default_value' => 'color-d',
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'array',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_61e94f768a691',
                                'label' => 'Hamburger',
                                'name' => 'hamburger',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'white' => 'White',
                                    'dark' => 'Dark',
                                    'black' => 'Black',
                                    'gray' => 'Gray',
                                    'color-a' => 'Dark Blue',
                                    'color-b' => 'Medium Blue',
                                    'color-c' => 'Light Blue',
                                    'color-d' => 'Pale Blue',
                                    'color-e' => 'Accent',
                                ),
                                'default_value' => 'black',
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'array',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_61e96bbbfae80',
                                'label' => 'Current menu item',
                                'name' => 'current_menu_item',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'white' => 'White',
                                    'dark' => 'Dark',
                                    'black' => 'Black',
                                    'gray' => 'Gray',
                                    'color-a' => 'Dark Blue',
                                    'color-b' => 'Medium Blue',
                                    'color-c' => 'Light Blue',
                                    'color-d' => 'Pale Blue',
                                    'color-e' => 'Accent',
                                ),
                                'default_value' => 'black',
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'array',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_61e96c6dc8c4e',
                                'label' => 'Button',
                                'name' => 'button',
                                'type' => 'group',
                                'instructions' => 'This style targets header NAV item/items which have \'btn\' class',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'acfe_seamless_style' => 0,
                                'acfe_group_modal' => 0,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_61e96c85c8c50',
                                        'label' => 'Color',
                                        'name' => 'color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'white' => 'White',
                                            'dark' => 'Dark',
                                            'black' => 'Black',
                                            'gray' => 'Gray',
                                            'color-a' => 'Dark Blue',
                                            'color-b' => 'Medium Blue',
                                            'color-c' => 'Light Blue',
                                            'color-d' => 'Pale Blue',
                                            'color-e' => 'Accent',
                                        ),
                                        'default_value' => false,
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'return_format' => 'array',
                                        'ajax' => 0,
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_61e96c76c8c4f',
                                        'label' => 'Label color',
                                        'name' => 'label_color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'white' => 'White',
                                            'dark' => 'Dark',
                                            'black' => 'Black',
                                            'gray' => 'Gray',
                                            'color-a' => 'Dark Blue',
                                            'color-b' => 'Medium Blue',
                                            'color-c' => 'Light Blue',
                                            'color-d' => 'Pale Blue',
                                            'color-e' => 'Accent',
                                        ),
                                        'default_value' => 'black',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'return_format' => 'array',
                                        'ajax' => 0,
                                        'placeholder' => '',
                                    ),
                                ),
                            ),
                        ),
                        'choices' => array(
                            'white' => 'White',
                            'dark' => 'Dark',
                            'black' => 'Black',
                            'gray' => 'Gray',
                            'color-a' => 'Dark Blue',
                            'color-b' => 'Medium Blue',
                            'color-c' => 'Light Blue',
                            'color-d' => 'Pale Blue',
                            'color-e' => 'Accent',
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_6137782263036',
                'label' => 'Footer',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_613777eb63030',
                'label' => 'Footer',
                'name' => 'footer',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_613777eb63031',
                        'label' => 'Logo',
                        'name' => 'logo',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'uploader' => '',
                        'acfe_thumbnail' => 0,
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_6138817f0bbe1',
                        'label' => 'Footer menu ID',
                        'name' => 'footer_menu_id',
                        'type' => 'text',
                        'instructions' => 'Don\'t change this.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_61e956618a9da',
                        'label' => 'Color',
                        'name' => 'color',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_61e9567ae6570',
                                'label' => 'Background',
                                'name' => 'background',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'white' => 'White',
                                    'dark' => 'Dark',
                                    'black' => 'Black',
                                    'gray' => 'Gray',
                                    'color-a' => 'Dark Blue',
                                    'color-b' => 'Medium Blue',
                                    'color-c' => 'Light Blue',
                                    'color-d' => 'Pale Blue',
                                    'color-e' => 'Accent',
                                ),
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'array',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_61e95689e6571',
                                'label' => 'Labels',
                                'name' => 'labels',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '40',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'white' => 'White',
                                    'dark' => 'Dark',
                                    'black' => 'Black',
                                    'gray' => 'Gray',
                                    'color-a' => 'Dark Blue',
                                    'color-b' => 'Medium Blue',
                                    'color-c' => 'Light Blue',
                                    'color-d' => 'Pale Blue',
                                    'color-e' => 'Accent',
                                ),
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'array',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_61e956a0e6572',
                                'label' => 'Rest',
                                'name' => 'rest',
                                'type' => 'select',
                                'instructions' => 'GDPR, Social icons..',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'white' => 'White',
                                    'dark' => 'Dark',
                                    'black' => 'Black',
                                    'gray' => 'Gray',
                                    'color-a' => 'Dark Blue',
                                    'color-b' => 'Medium Blue',
                                    'color-c' => 'Light Blue',
                                    'color-d' => 'Pale Blue',
                                    'color-e' => 'Accent',
                                ),
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'array',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                        ),
                        'choices' => array(
                            'white' => 'White',
                            'dark' => 'Dark',
                            'black' => 'Black',
                            'gray' => 'Gray',
                            'color-a' => 'Dark Blue',
                            'color-b' => 'Medium Blue',
                            'color-c' => 'Light Blue',
                            'color-d' => 'Pale Blue',
                            'color-e' => 'Accent',
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_6137782d63037',
                'label' => '404',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6137780163032',
                'label' => '404 page',
                'name' => '404_page',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6137780763033',
                        'label' => 'Content',
                        'name' => 'content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'gardp_settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'permalink',
            1 => 'block_editor',
            2 => 'the_content',
            3 => 'excerpt',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'slug',
            8 => 'author',
            9 => 'format',
            10 => 'page_attributes',
            11 => 'featured_image',
            12 => 'categories',
            13 => 'tags',
            14 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => array(
            0 => 'json',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
    
    endif;		

?>